import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:provider/provider.dart';
import '../../models/diamond_package_model.dart';
import '../../models/payment_method_model.dart';
import '../../models/topup_request_model.dart';
import '../../providers/user_provider.dart';
import '../../services/monetization_service.dart';

class ManualTopUpScreen extends StatefulWidget {
  final DiamondPackageModel package;
  final List<PaymentMethodModel> availableMethods;
  final PaymentMethodModel initialMethod;

  const ManualTopUpScreen({
    super.key,
    required this.package,
    required this.availableMethods,
    required this.initialMethod,
  });

  @override
  State<ManualTopUpScreen> createState() => _ManualTopUpScreenState();
}

class _ManualTopUpScreenState extends State<ManualTopUpScreen> {
  late PaymentMethodModel _selectedMethod;
  File? _receiptImage;
  bool _isUploading = false;
  final ImagePicker _picker = ImagePicker();
  final MonetizationService _monetizationService = MonetizationService();

  @override
  void initState() {
    super.initState();
    _selectedMethod = widget.initialMethod;
  }

  Future<void> _pickImage() async {
    final pickedFile = await _picker.pickImage(source: ImageSource.gallery);
    if (pickedFile != null) {
      setState(() {
        _receiptImage = File(pickedFile.path);
      });
    }
  }

  Future<void> _submitRequest() async {
    if (_receiptImage == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please upload a screenshot of your receipt')),
      );
      return;
    }

    setState(() {
      _isUploading = true;
    });

    try {
      final userProvider = Provider.of<UserProvider>(context, listen: false);
      final userId = userProvider.currentUser?.uid;

      if (userId == null) throw Exception("User not logged in");

      // 1. Upload Image to Storage
      final String fileName = '${DateTime.now().millisecondsSinceEpoch}.jpg';
      final Reference ref = FirebaseStorage.instance
          .ref()
          .child('topup_receipts')
          .child(userId)
          .child(fileName);

      final UploadTask uploadTask = ref.putFile(_receiptImage!);
      final TaskSnapshot snapshot = await uploadTask;
      final String downloadUrl = await snapshot.ref.getDownloadURL();

      // 2. Submit Request to Firestore
      final request = TopUpRequestModel(
        id: '', // Generated by Firestore
        userId: userId,
        packageId: widget.package.id,
        paymentMethodId: _selectedMethod.id,
        receiptImageUrl: downloadUrl,
        diamondsRequested: widget.package.diamonds,
      );

      final success = await _monetizationService.submitTopUpRequest(request);

      if (success) {
        if (!mounted) return;
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Top-up request submitted successfully! Pending approval.')),
        );
        Navigator.pop(context); // Go back after success
      } else {
        throw Exception("Failed to save request to database");
      }
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error: ${e.toString()}')),
      );
    } finally {
      if (mounted) {
        setState(() {
          _isUploading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        title: const Text('Manual Top Up'),
        backgroundColor: const Color(0xFF1E1E1E),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // 1. Package Summary
            Container(
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                gradient: const LinearGradient(colors: [Color(0xFFFF1493), Color(0xFFFF69B4)]),
                borderRadius: BorderRadius.circular(16),
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text(
                        'You are purchasing:',
                        style: TextStyle(color: Colors.white70, fontSize: 14),
                      ),
                      const SizedBox(height: 8),
                      Row(
                        children: [
                          const Icon(Icons.monetization_on, color: Colors.yellow, size: 24),
                          const SizedBox(width: 8),
                          Text(
                            '${widget.package.diamonds} Diamonds',
                            style: const TextStyle(
                              color: Colors.white,
                              fontSize: 24,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                  Text(
                    widget.package.price,
                    style: const TextStyle(
                      color: Colors.white,
                      fontSize: 28,
                      fontWeight: FontWeight.w900,
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 30),

            // 2. Select Payment Method
            const Text(
              'Select Payment Method',
              style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 12),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 16),
              decoration: BoxDecoration(
                color: const Color(0xFF1E1E1E),
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: Colors.white24),
              ),
              child: DropdownButtonHideUnderline(
                child: DropdownButton<PaymentMethodModel>(
                  value: _selectedMethod,
                  isExpanded: true,
                  dropdownColor: const Color(0xFF1E1E1E),
                  icon: const Icon(Icons.arrow_drop_down, color: Colors.white),
                  items: widget.availableMethods.map((method) {
                    return DropdownMenuItem(
                      value: method,
                      child: Text(
                        method.name,
                        style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
                      ),
                    );
                  }).toList(),
                  onChanged: (value) {
                    if (value != null) {
                      setState(() {
                        _selectedMethod = value;
                      });
                    }
                  },
                ),
              ),
            ),
            const SizedBox(height: 30),

            // 3. Payment Instructions
            const Text(
              'Payment Instructions',
              style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 12),
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: Colors.blue.withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: Colors.blue.withValues(alpha: 0.3)),
              ),
              child: Text(
                _selectedMethod.instructions.isNotEmpty
                    ? _selectedMethod.instructions
                    : 'Please transfer ${widget.package.price} to our ${_selectedMethod.name} account and upload the receipt.',
                style: const TextStyle(color: Colors.white, fontSize: 16, height: 1.5),
              ),
            ),
            const SizedBox(height: 30),

            // 4. Upload Receipt
            const Text(
              'Upload Receipt Screenshot',
              style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 12),
            GestureDetector(
              onTap: _pickImage,
              child: Container(
                height: 200,
                width: double.infinity,
                decoration: BoxDecoration(
                  color: const Color(0xFF1E1E1E),
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: Colors.white24, style: BorderStyle.solid),
                ),
                child: _receiptImage != null
                    ? ClipRRect(
                        borderRadius: BorderRadius.circular(12),
                        child: Image.file(_receiptImage!, fit: BoxFit.cover),
                      )
                    : Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Icon(Icons.cloud_upload, color: Colors.white.withValues(alpha: 0.5), size: 48),
                          const SizedBox(height: 16),
                          Text(
                            'Tap to Browse Image',
                            style: TextStyle(color: Colors.white.withValues(alpha: 0.5)),
                          ),
                        ],
                      ),
              ),
            ),
            const SizedBox(height: 40),

            // 5. Submit Button
            SizedBox(
              width: double.infinity,
              height: 56,
              child: ElevatedButton(
                onPressed: _isUploading ? null : _submitRequest,
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFFFF1493),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                ),
                child: _isUploading
                    ? const CircularProgressIndicator(color: Colors.white)
                    : const Text(
                        'Submit Request',
                        style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold),
                      ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
