// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9TKP-TFluGRMV04kTe3L7cijNugc-iRM',
    appId: '1:351905956852:web:9835da2a1db9a4945a2fa1',
    messagingSenderId: '351905956852',
    projectId: 'dating-live-app-477af',
    authDomain: 'dating-live-app-477af.firebaseapp.com',
    storageBucket: 'dating-live-app-477af.firebasestorage.app',
    measurementId: 'G-W0EVBE5MMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzXH0KH0UzjOt2AERgaX4SVNS6OGWygCY',
    appId: '1:351905956852:android:d47fcd4bc1f9efab5a2fa1',
    messagingSenderId: '351905956852',
    projectId: 'dating-live-app-477af',
    storageBucket: 'dating-live-app-477af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAliTT_14b2hq63CC0Y_cw6Rd0fWmtlZs',
    appId: '1:351905956852:ios:7115ac61ce37be935a2fa1',
    messagingSenderId: '351905956852',
    projectId: 'dating-live-app-477af',
    storageBucket: 'dating-live-app-477af.firebasestorage.app',
    androidClientId: '351905956852-vaqrgg6qdbjlge2r9b9v12nofltebkvu.apps.googleusercontent.com',
    iosClientId: '351905956852-26jsj1e1u32vblrkqege9tb058otp6qk.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingLiveApp',
  );
}
