class CountryUtils {
  static const Map<String, String> countryFlags = {
    'Afghanistan': '🇦🇫',
    'Albania': '🇦🇱',
    'Algeria': '🇩🇿',
    'American Samoa': '🇦🇸',
    'Andorra': '🇦🇩',
    'Angola': '🇦🇴',
    'Anguilla': '🇦🇮',
    'Antarctica': '🇦🇶',
    'Antigua and Barbuda': '🇦🇬',
    'Argentina': '🇦🇷',
    'Armenia': '🇦🇲',
    'Aruba': '🇦🇼',
    'Australia': '🇦🇺',
    'Austria': '🇦🇹',
    'Azerbaijan': '🇦🇿',
    'Bahamas': '🇧🇸',
    'Bahrain': '🇧🇭',
    'Bangladesh': '🇧🇩',
    'Barbados': '🇧🇧',
    'Belarus': '🇧🇾',
    'Belgium': '🇧🇪',
    'Belize': '🇧🇿',
    'Benin': '🇧🇯',
    'Bermuda': '🇧🇲',
    'Bhutan': '🇧🇹',
    'Bolivia': '🇧🇴',
    'Bosnia and Herzegovina': '🇧🇦',
    'Botswana': '🇧🇼',
    'Brazil': '🇧🇷',
    'British Virgin Islands': '🇻🇬',
    'Brunei': '🇧🇳',
    'Bulgaria': '🇧🇬',
    'Burkina Faso': '🇧🇫',
    'Burundi': '🇧🇮',
    'Cabo Verde': '🇨🇻',
    'Cambodia': '🇰🇭',
    'Cameroon': '🇨🇲',
    'Canada': '🇨🇦',
    'Cayman Islands': '🇰🇾',
    'Central African Republic': '🇨🇫',
    'Chad': '🇹🇩',
    'Chile': '🇨🇱',
    'China': '🇨🇳',
    'Colombia': '🇨🇴',
    'Comoros': '🇰🇲',
    'Congo': '🇨🇬',
    'Cook Islands': '🇨🇰',
    'Costa Rica': '🇨🇷',
    'Croatia': '🇭🇷',
    'Cuba': '🇨🇺',
    'Curaçao': '🇨🇼',
    'Cyprus': '🇨🇾',
    'Czech Republic': '🇨🇿',
    'Denmark': '🇩🇰',
    'Djibouti': '🇩🇯',
    'Dominica': '🇩🇲',
    'Dominican Republic': '🇩🇴',
    'Ecuador': '🇪🇨',
    'Egypt': '🇪🇬',
    'El Salvador': '🇸🇻',
    'Equatorial Guinea': '🇬🇶',
    'Eritrea': '🇪🇷',
    'Estonia': '🇪🇪',
    'Eswatini': '🇸🇿',
    'Ethiopia': '🇪🇹',
    'Falkland Islands': '🇫🇰',
    'Faroe Islands': '🇫🇴',
    'Fiji': '🇫🇯',
    'Finland': '🇫🇮',
    'France': '🇫🇷',
    'French Guiana': '🇬🇫',
    'French Polynesia': '🇵🇫',
    'Gabon': '🇬🇦',
    'Gambia': '🇬🇲',
    'Georgia': '🇬🇪',
    'Germany': '🇩🇪',
    'Ghana': '🇬🇭',
    'Gibraltar': '🇬🇮',
    'Greece': '🇬🇷',
    'Greenland': '🇬🇱',
    'Grenada': '🇬🇩',
    'Guadeloupe': '🇬🇵',
    'Guam': '🇬🇺',
    'Guatemala': '🇬🇹',
    'Guernsey': '🇬🇬',
    'Guinea': '🇬🇳',
    'Guinea-Bissau': '🇬🇼',
    'Guyana': '🇬🇾',
    'Haiti': '🇭🇹',
    'Honduras': '🇭🇳',
    'Hong Kong': '🇭🇰',
    'Hungary': '🇭🇺',
    'Iceland': '🇮🇸',
    'India': '🇮🇳',
    'Indonesia': '🇮🇩',
    'Iran': '🇮🇷',
    'Iraq': '🇮🇶',
    'Ireland': '🇮🇪',
    'Isle of Man': '🇮🇲',
    'Israel': '🇮🇱',
    'Italy': '🇮🇹',
    'Ivory Coast': '🇨🇮',
    'Jamaica': '🇯🇲',
    'Japan': '🇯🇵',
    'Jersey': '🇯🇪',
    'Jordan': '🇯🇴',
    'Kazakhstan': '🇰🇿',
    'Kenya': '🇰🇪',
    'Kiribati': '🇰🇮',
    'Kosovo': '🇽🇰',
    'Kuwait': '🇰🇼',
    'Kyrgyzstan': '🇰🇬',
    'Laos': '🇱🇦',
    'Latvia': '🇱🇻',
    'Lebanon': '🇱🇧',
    'Lesotho': '🇱🇸',
    'Liberia': '🇱🇷',
    'Libya': '🇱🇾',
    'Liechtenstein': '🇱🇮',
    'Lithuania': '🇱🇹',
    'Luxembourg': '🇱🇺',
    'Macau': '🇲🇴',
    'Madagascar': '🇲🇬',
    'Malawi': '🇲🇼',
    'Malaysia': '🇲🇾',
    'Maldives': '🇲🇻',
    'Mali': '🇲🇱',
    'Malta': '🇲🇹',
    'Marshall Islands': '🇲🇭',
    'Martinique': '🇲🇶',
    'Mauritania': '🇲🇷',
    'Mauritius': '🇲🇺',
    'Mayotte': '🇾🇹',
    'Mexico': '🇲🇽',
    'Micronesia': '🇫🇲',
    'Moldova': '🇲🇩',
    'Monaco': '🇲🇨',
    'Mongolia': '🇲🇳',
    'Montenegro': '🇲🇪',
    'Montserrat': '🇲🇸',
    'Morocco': '🇲🇦',
    'Mozambique': '🇲🇿',
    'Myanmar': '🇲🇲',
    'Namibia': '🇳🇦',
    'Nauru': '🇳🇷',
    'Nepal': '🇳🇵',
    'Netherlands': '🇳🇱',
    'New Caledonia': '🇳🇨',
    'New Zealand': '🇳🇿',
    'Nicaragua': '🇳🇮',
    'Niger': '🇳🇪',
    'Nigeria': '🇳🇬',
    'Niue': '🇳🇺',
    'North Korea': '🇰🇵',
    'North Macedonia': '🇲🇰',
    'Northern Mariana Islands': '🇲🇵',
    'Norway': '🇳🇴',
    'Oman': '🇴🇲',
    'Pakistan': '🇵🇰',
    'Palau': '🇵🇼',
    'Palestine': '🇵🇸',
    'Panama': '🇵🇦',
    'Papua New Guinea': '🇵🇬',
    'Paraguay': '🇵🇾',
    'Peru': '🇵🇪',
    'Philippines': '🇵🇭',
    'Poland': '🇵🇱',
    'Portugal': '🇵🇹',
    'Puerto Rico': '🇵🇷',
    'Qatar': '🇶🇦',
    'Réunion': '🇷🇪',
    'Romania': '🇷🇴',
    'Russia': '🇷🇺',
    'Rwanda': '🇷🇼',
    'Saint Barthélemy': '🇧🇱',
    'Saint Helena': '🇸🇭',
    'Saint Kitts and Nevis': '🇰🇳',
    'Saint Lucia': '🇱🇨',
    'Saint Martin': '🇲🇫',
    'Saint Pierre and Miquelon': '🇵🇲',
    'Saint Vincent and the Grenadines': '🇻🇨',
    'Samoa': '🇼🇸',
    'San Marino': '🇸🇲',
    'Sao Tome and Principe': '🇸🇹',
    'Saudi Arabia': '🇸🇦',
    'Senegal': '🇸🇳',
    'Serbia': '🇷🇸',
    'Seychelles': '🇸🇨',
    'Sierra Leone': '🇸🇱',
    'Singapore': '🇸🇬',
    'Sint Maarten': '🇸🇽',
    'Slovakia': '🇸🇰',
    'Slovenia': '🇸🇮',
    'Solomon Islands': '🇸🇧',
    'Somalia': '🇸🇴',
    'South Africa': '🇿🇦',
    'South Korea': '🇰🇷',
    'South Sudan': '🇸🇸',
    'Spain': '🇪🇸',
    'Sri Lanka': '🇱🇰',
    'Sudan': '🇸🇩',
    'Suriname': '🇸🇷',
    'Svalbard and Jan Mayen': '🇸🇯',
    'Sweden': '🇸🇪',
    'Switzerland': '🇨🇭',
    'Syria': '🇸🇾',
    'Taiwan': '🇹🇼',
    'Tajikistan': '🇹🇯',
    'Tanzania': '🇹🇿',
    'Thailand': '🇹🇭',
    'Timor-Leste': '🇹🇱',
    'Togo': '🇹🇬',
    'Tokelau': '🇹🇰',
    'Tonga': '🇹🇴',
    'Trinidad and Tobago': '🇹🇹',
    'Tunisia': '🇹🇳',
    'Turkey': '🇹🇷',
    'Turkmenistan': '🇹🇲',
    'Turks and Caicos Islands': '🇹🇨',
    'Tuvalu': '🇹🇻',
    'U.S. Virgin Islands': '🇻🇮',
    'Uganda': '🇺🇬',
    'Ukraine': '🇺🇦',
    'United Arab Emirates': '🇦🇪',
    'United Kingdom': '🇬🇧',
    'United States': '🇺🇸',
    'Uruguay': '🇺🇾',
    'Uzbekistan': '🇺🇿',
    'Vanuatu': '🇻🇺',
    'Vatican City': '🇻🇦',
    'Venezuela': '🇻🇪',
    'Vietnam': '🇻🇳',
    'Wallis and Futuna': '🇼🇫',
    'Western Sahara': '🇪🇭',
    'Yemen': '🇾🇪',
    'Zambia': '🇿🇲',
    'Zimbabwe': '🇿🇼',
  };

  static List<String> get allCountries => countryFlags.keys.toList()..sort();

  static String getFlag(String countryName) {
    return countryFlags[countryName] ?? '🌍';
  }

  static const List<String> allLanguages = [
    'English', 'Sinhala', 'Tamil', 'Hindi', 'Urdu', 'Bengali', 'Punjabi', 'Telugu', 'Marathi', 'Gujarati', 'Kannada', 'Malayalam', 'Oriya', 'Bhojpuri', 'Maithili', 'Sindhi', 'Pashto',
    'Arabic', 'Farsi', 'Kurdish', 'Turkish', 'Hebrew', 'Amharic', 'Somali',
    'Chinese', 'Japanese', 'Korean', 'Vietnamese', 'Thai', 'Khmer', 'Burmese', 'Malay', 'Indonesian', 'Tagalog', 'Sundanese',
    'Spanish', 'French', 'Portuguese', 'German', 'Italian', 'Russian', 'Dutch', 'Greek', 'Turkish', 'Polish', 'Ukrainian', 'Romanian', 'Czech', 'Hungarian', 'Swedish', 'Norwegian', 'Danish', 'Finnish', 'Bulgarian', 'Serbian', 'Croatian', 'Lithuanian', 'Latvian', 'Estonian',
    'Hausa', 'Yoruba', 'Igbo', 'Fula', 'Oromo', 'Azerbaijani', 'Uzbek'
  ];
}
